flags: {}
packages:
- '.'
- ./liquid-fixpoint
extra-deps:
- dotgen-0.4.2
- fgl-visualize-0.1.0.1
- intern-0.9.1.4
- located-base-0.1.1.0
- intern-0.9.1.4
- process-1.4.2.0
compiler-check: newer-minor
resolver: lts-6.24
