#!/bin/zsh

test_benchmark() {
	if [[ $# -ne 1 ]]; then
		echo "usage: test <Symmetry test file>"
		return 1
    fi

    stack install

    local file=$1
    local exe=${file:r}

    stack ghc -- $file -o $exe
    ./$exe --verify

    local bmk_res=$?
    if  [[ $bmk_res -eq 0 ]];
    then
        return 0
    fi

    local symcheck="${file:h}/.symcheck"
    local pml="$symcheck/out.pml"

    nohup ispin $pml &
}

test_benchmark $@
