#!/bin/zsh

test_benchmark() {
	if [[ $# -ne 1 ]]; then
        echo "usage: test <Symmetry test exec>"
		return 1
    fi

    local exe=$1

    ./$exe --verify

    local bmk_res=$?
    if  [[ $bmk_res -eq 0 ]]; then
        return 0
    fi

    local symcheck="${exe:h}/.symcheck"
    local pml="$symcheck/out.pml"

    echo "Counter example:"
    spin -p -t $pml
}

test_benchmark $@
