flags: {}

packages:
- '.'
- location:
    git:    https://github.com/ucsd-progsys/liquid-fixpoint.git
    commit: aa550dcb492636f0b02d03abfcc94ac7e1aadf6b

extra-deps:
- plugins-1.5.5.0
- located-base-0.1.0.0
- ascii-progress-0.3.2.0
- intern-0.9.1.4
- concurrent-output-1.7.3

resolver: lts-3.8
